// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addArtistToCategory = `-- name: AddArtistToCategory :exec
INSERT OR IGNORE INTO artist_categories (artist_id, category_id) VALUES (?, ?)
`

type AddArtistToCategoryParams struct {
	ArtistID   string `json:"artist_id"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) AddArtistToCategory(ctx context.Context, arg AddArtistToCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addArtistToCategory, arg.ArtistID, arg.CategoryID)
	return err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (id, name, fetch_mode) VALUES (?, ?, ?) RETURNING id, name, fetch_mode, created_at, updated_at
`

type CreateArtistParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	FetchMode string `json:"fetch_mode"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, arg.ID, arg.Name, arg.FetchMode)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FetchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists WHERE id = ?
`

func (q *Queries) DeleteArtist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArtist, id)
	return err
}

const deleteArtistCategoriesByArtist = `-- name: DeleteArtistCategoriesByArtist :exec
DELETE FROM artist_categories WHERE artist_id = ?
`

func (q *Queries) DeleteArtistCategoriesByArtist(ctx context.Context, artistID string) error {
	_, err := q.db.ExecContext(ctx, deleteArtistCategoriesByArtist, artistID)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, fetch_mode, created_at, updated_at FROM artists WHERE id = ?
`

func (q *Queries) GetArtist(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FetchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistCategoryCount = `-- name: GetArtistCategoryCount :one
SELECT COUNT(*) as count FROM artist_categories WHERE artist_id = ?
`

func (q *Queries) GetArtistCategoryCount(ctx context.Context, artistID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getArtistCategoryCount, artistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArtistCategoryPairs = `-- name: ListArtistCategoryPairs :many
SELECT ac.artist_id, c.id AS category_id, c.name AS category_name
FROM artist_categories ac
JOIN categories c ON c.id = ac.category_id
WHERE c.user_id = ?
ORDER BY c.name
`

type ListArtistCategoryPairsRow struct {
	ArtistID     string `json:"artist_id"`
	CategoryID   string `json:"category_id"`
	CategoryName string `json:"category_name"`
}

// Every artist-to-category membership for one user, in one round trip. Replaces the
// per-category fetch the category tree fires on mount.
func (q *Queries) ListArtistCategoryPairs(ctx context.Context, userID sql.NullString) ([]ListArtistCategoryPairsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistCategoryPairs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistCategoryPairsRow{}
	for rows.Next() {
		var i ListArtistCategoryPairsRow
		if err := rows.Scan(&i.ArtistID, &i.CategoryID, &i.CategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistClaimedCounts = `-- name: ListArtistClaimedCounts :many
SELECT p.artist_id, COUNT(DISTINCT e.id) AS claimed_count
FROM performances p
JOIN events e ON e.id = p.event_id
JOIN library_entries le ON le.event_id = e.id
WHERE p.artist_id IS NOT NULL AND le.user_id = ?
GROUP BY p.artist_id
`

type ListArtistClaimedCountsRow struct {
	ArtistID     sql.NullString `json:"artist_id"`
	ClaimedCount int64          `json:"claimed_count"`
}

// How many of an artist's events this user has claimed (any status).
func (q *Queries) ListArtistClaimedCounts(ctx context.Context, userID string) ([]ListArtistClaimedCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistClaimedCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistClaimedCountsRow{}
	for rows.Next() {
		var i ListArtistClaimedCountsRow
		if err := rows.Scan(&i.ArtistID, &i.ClaimedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistCountryCounts = `-- name: ListArtistCountryCounts :many
SELECT p.artist_id, v.country_code, COUNT(DISTINCT e.id) AS n
FROM performances p
JOIN events e ON e.id = p.event_id
JOIN venues v ON v.id = e.venue_id
WHERE p.artist_id IS NOT NULL
  AND v.country_code IS NOT NULL
  AND e.listing_state = 'listed'
  AND date(e.start_date) >= date('now')
GROUP BY p.artist_id, v.country_code
`

type ListArtistCountryCountsRow struct {
	ArtistID    sql.NullString `json:"artist_id"`
	CountryCode sql.NullString `json:"country_code"`
	N           int64          `json:"n"`
}

// Countries an artist's upcoming listed events are in - the flag row on the artist page and
// in the category tree.
func (q *Queries) ListArtistCountryCounts(ctx context.Context) ([]ListArtistCountryCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistCountryCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistCountryCountsRow{}
	for rows.Next() {
		var i ListArtistCountryCountsRow
		if err := rows.Scan(&i.ArtistID, &i.CountryCode, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistEventCounts = `-- name: ListArtistEventCounts :many
SELECT p.artist_id,
       COUNT(DISTINCT e.id) AS event_count,
       COUNT(DISTINCT CASE
           WHEN e.listing_state = 'listed' AND date(e.start_date) >= date('now')
           THEN e.id END) AS upcoming_listed_count
FROM performances p
JOIN events e ON e.id = p.event_id
WHERE p.artist_id IS NOT NULL
GROUP BY p.artist_id
`

type ListArtistEventCountsRow struct {
	ArtistID            sql.NullString `json:"artist_id"`
	EventCount          int64          `json:"event_count"`
	UpcomingListedCount int64          `json:"upcoming_listed_count"`
}

// Per-artist totals. upcoming_listed is what the tree's "dormant" marker reads.
func (q *Queries) ListArtistEventCounts(ctx context.Context) ([]ListArtistEventCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistEventCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistEventCountsRow{}
	for rows.Next() {
		var i ListArtistEventCountsRow
		if err := rows.Scan(&i.ArtistID, &i.EventCount, &i.UpcomingListedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, fetch_mode, created_at, updated_at FROM artists ORDER BY name
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FetchMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsByCategory = `-- name: ListArtistsByCategory :many
SELECT a.id, a.name, a.fetch_mode, a.created_at, a.updated_at
FROM artists a JOIN artist_categories ac ON a.id = ac.artist_id
WHERE ac.category_id = ? ORDER BY a.name
`

func (q *Queries) ListArtistsByCategory(ctx context.Context, categoryID string) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtistsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FetchMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArtistFromCategory = `-- name: RemoveArtistFromCategory :exec
DELETE FROM artist_categories WHERE artist_id = ? AND category_id = ?
`

type RemoveArtistFromCategoryParams struct {
	ArtistID   string `json:"artist_id"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) RemoveArtistFromCategory(ctx context.Context, arg RemoveArtistFromCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeArtistFromCategory, arg.ArtistID, arg.CategoryID)
	return err
}

const setArtistFetchMode = `-- name: SetArtistFetchMode :one
UPDATE artists SET fetch_mode = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, fetch_mode, created_at, updated_at
`

type SetArtistFetchModeParams struct {
	FetchMode string `json:"fetch_mode"`
	ID        string `json:"id"`
}

func (q *Queries) SetArtistFetchMode(ctx context.Context, arg SetArtistFetchModeParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, setArtistFetchMode, arg.FetchMode, arg.ID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FetchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, fetch_mode, created_at, updated_at
`

type UpdateArtistParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, updateArtist, arg.Name, arg.ID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FetchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
