// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addPerformance = `-- name: AddPerformance :exec
INSERT INTO performances (id, event_id, artist_id, artist_name, is_headliner, date, venue_name)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddPerformanceParams struct {
	ID          string         `json:"id"`
	EventID     string         `json:"event_id"`
	ArtistID    sql.NullString `json:"artist_id"`
	ArtistName  string         `json:"artist_name"`
	IsHeadliner int64          `json:"is_headliner"`
	Date        sql.NullString `json:"date"`
	VenueName   sql.NullString `json:"venue_name"`
}

// One artist at an event. artist_id NULL = name-only. No unique key: an artist may
// appear twice at one festival (different date/venue).
func (q *Queries) AddPerformance(ctx context.Context, arg AddPerformanceParams) error {
	_, err := q.db.ExecContext(ctx, addPerformance,
		arg.ID,
		arg.EventID,
		arg.ArtistID,
		arg.ArtistName,
		arg.IsHeadliner,
		arg.Date,
		arg.VenueName,
	)
	return err
}

const countArtistSourceEvents = `-- name: CountArtistSourceEvents :one
SELECT COUNT(DISTINCT e.id) AS count FROM events e
JOIN performances p ON e.id = p.event_id
WHERE p.artist_id = ? AND e.source = ?
`

type CountArtistSourceEventsParams struct {
	ArtistID sql.NullString `json:"artist_id"`
	Source   string         `json:"source"`
}

func (q *Queries) CountArtistSourceEvents(ctx context.Context, arg CountArtistSourceEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtistSourceEvents, arg.ArtistID, arg.Source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllUnclaimedEvents = `-- name: DeleteAllUnclaimedEvents :exec
DELETE FROM events
WHERE NOT EXISTS (SELECT 1 FROM library_entries le WHERE le.event_id = events.id)
`

// "Clear all events" = drop everything no one has claimed (claimed survive via RESTRICT predicate).
func (q *Queries) DeleteAllUnclaimedEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUnclaimedEvents)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ?
`

// Guarded by ON DELETE RESTRICT: errors if a library_entries row references it.
func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deletePastUnclaimedTmEvents = `-- name: DeletePastUnclaimedTmEvents :exec
DELETE FROM events
WHERE source = 'ticketmaster'
  AND date(start_date) < date('now')
  AND NOT EXISTS (SELECT 1 FROM library_entries le WHERE le.event_id = events.id)
`

// On-demand purge of past Ticketmaster events no one claimed. Claimed events are safe.
func (q *Queries) DeletePastUnclaimedTmEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePastUnclaimedTmEvents)
	return err
}

const deletePerformancesByEvent = `-- name: DeletePerformancesByEvent :exec
DELETE FROM performances WHERE event_id = ?
`

func (q *Queries) DeletePerformancesByEvent(ctx context.Context, eventID string) error {
	_, err := q.db.ExecContext(ctx, deletePerformancesByEvent, eventID)
	return err
}

const deleteUnclaimedArtistEvents = `-- name: DeleteUnclaimedArtistEvents :exec
DELETE FROM events
WHERE source = 'ticketmaster'
  AND id IN (SELECT event_id FROM performances WHERE artist_id = ?)
  AND NOT EXISTS (SELECT 1 FROM library_entries le WHERE le.event_id = events.id)
`

// Clear one artist's un-claimed TM events (claim-safe; claimed survive).
func (q *Queries) DeleteUnclaimedArtistEvents(ctx context.Context, artistID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteUnclaimedArtistEvents, artistID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at FROM events WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.About,
		&i.StartDate,
		&i.EndDate,
		&i.HasTime,
		&i.VenueID,
		&i.Url,
		&i.ImageUrl,
		&i.TicketOptions,
		&i.ListingState,
		&i.Extra,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySource = `-- name: GetEventBySource :one
SELECT id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at FROM events WHERE source = ? AND source_id = ?
`

type GetEventBySourceParams struct {
	Source   string         `json:"source"`
	SourceID sql.NullString `json:"source_id"`
}

func (q *Queries) GetEventBySource(ctx context.Context, arg GetEventBySourceParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventBySource, arg.Source, arg.SourceID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.About,
		&i.StartDate,
		&i.EndDate,
		&i.HasTime,
		&i.VenueID,
		&i.Url,
		&i.ImageUrl,
		&i.TicketOptions,
		&i.ListingState,
		&i.Extra,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (id, source, source_id, name, kind, description, about,
                    start_date, end_date, has_time, venue_id, url, image_url,
                    ticket_options, listing_state)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at
`

type InsertEventParams struct {
	ID            string         `json:"id"`
	Source        string         `json:"source"`
	SourceID      sql.NullString `json:"source_id"`
	Name          string         `json:"name"`
	Kind          string         `json:"kind"`
	Description   sql.NullString `json:"description"`
	About         sql.NullString `json:"about"`
	StartDate     string         `json:"start_date"`
	EndDate       sql.NullString `json:"end_date"`
	HasTime       int64          `json:"has_time"`
	VenueID       sql.NullString `json:"venue_id"`
	Url           sql.NullString `json:"url"`
	ImageUrl      sql.NullString `json:"image_url"`
	TicketOptions string         `json:"ticket_options"`
	ListingState  string         `json:"listing_state"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.ID,
		arg.Source,
		arg.SourceID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.About,
		arg.StartDate,
		arg.EndDate,
		arg.HasTime,
		arg.VenueID,
		arg.Url,
		arg.ImageUrl,
		arg.TicketOptions,
		arg.ListingState,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.About,
		&i.StartDate,
		&i.EndDate,
		&i.HasTime,
		&i.VenueID,
		&i.Url,
		&i.ImageUrl,
		&i.TicketOptions,
		&i.ListingState,
		&i.Extra,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPerformances = `-- name: ListAllPerformances :many
SELECT id, event_id, artist_id, artist_name, is_headliner, date, venue_name
FROM performances ORDER BY is_headliner DESC
`

type ListAllPerformancesRow struct {
	ID          string         `json:"id"`
	EventID     string         `json:"event_id"`
	ArtistID    sql.NullString `json:"artist_id"`
	ArtistName  string         `json:"artist_name"`
	IsHeadliner int64          `json:"is_headliner"`
	Date        sql.NullString `json:"date"`
	VenueName   sql.NullString `json:"venue_name"`
}

func (q *Queries) ListAllPerformances(ctx context.Context) ([]ListAllPerformancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPerformances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPerformancesRow{}
	for rows.Next() {
		var i ListAllPerformancesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ArtistID,
			&i.ArtistName,
			&i.IsHeadliner,
			&i.Date,
			&i.VenueName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at FROM events ORDER BY start_date ASC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.About,
			&i.StartDate,
			&i.EndDate,
			&i.HasTime,
			&i.VenueID,
			&i.Url,
			&i.ImageUrl,
			&i.TicketOptions,
			&i.ListingState,
			&i.Extra,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByArtist = `-- name: ListEventsByArtist :many
SELECT e.id, e.source, e.source_id, e.name, e.kind, e.description, e.about, e.start_date, e.end_date, e.has_time, e.venue_id, e.url, e.image_url, e.ticket_options, e.listing_state, e.extra, e.discovered_at, e.created_at, e.updated_at FROM events e
JOIN performances p ON e.id = p.event_id
WHERE p.artist_id = ?
GROUP BY e.id
ORDER BY e.start_date ASC
`

// Events with a performance by this tracked artist. GROUP BY: an artist may have >1 performance
// at one event (festival two-sets), so de-dup to one event row.
func (q *Queries) ListEventsByArtist(ctx context.Context, artistID sql.NullString) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.About,
			&i.StartDate,
			&i.EndDate,
			&i.HasTime,
			&i.VenueID,
			&i.Url,
			&i.ImageUrl,
			&i.TicketOptions,
			&i.ListingState,
			&i.Extra,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDateRange = `-- name: ListEventsByDateRange :many
SELECT id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at FROM events WHERE start_date >= ? AND start_date <= ? ORDER BY start_date ASC
`

type ListEventsByDateRangeParams struct {
	StartDate   string `json:"start_date"`
	StartDate_2 string `json:"start_date_2"`
}

func (q *Queries) ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByDateRange, arg.StartDate, arg.StartDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.About,
			&i.StartDate,
			&i.EndDate,
			&i.HasTime,
			&i.VenueID,
			&i.Url,
			&i.ImageUrl,
			&i.TicketOptions,
			&i.ListingState,
			&i.Extra,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformancesByEvent = `-- name: ListPerformancesByEvent :many
SELECT id, event_id, artist_id, artist_name, is_headliner, date, venue_name
FROM performances WHERE event_id = ?
ORDER BY is_headliner DESC, date, artist_name
`

type ListPerformancesByEventRow struct {
	ID          string         `json:"id"`
	EventID     string         `json:"event_id"`
	ArtistID    sql.NullString `json:"artist_id"`
	ArtistName  string         `json:"artist_name"`
	IsHeadliner int64          `json:"is_headliner"`
	Date        sql.NullString `json:"date"`
	VenueName   sql.NullString `json:"venue_name"`
}

func (q *Queries) ListPerformancesByEvent(ctx context.Context, eventID string) ([]ListPerformancesByEventRow, error) {
	rows, err := q.db.QueryContext(ctx, listPerformancesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformancesByEventRow{}
	for rows.Next() {
		var i ListPerformancesByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ArtistID,
			&i.ArtistName,
			&i.IsHeadliner,
			&i.Date,
			&i.VenueName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEvents = `-- name: SearchEvents :many
SELECT e.id, e.source, e.source_id, e.name, e.kind, e.description, e.about, e.start_date, e.end_date, e.has_time, e.venue_id, e.url, e.image_url, e.ticket_options, e.listing_state, e.extra, e.discovered_at, e.created_at, e.updated_at FROM events e
LEFT JOIN venues v ON e.venue_id = v.id
LEFT JOIN performances p ON e.id = p.event_id
WHERE e.name LIKE ? OR v.name LIKE ? OR p.artist_name LIKE ?
GROUP BY e.id
ORDER BY e.start_date ASC
`

type SearchEventsParams struct {
	Name       string `json:"name"`
	Name_2     string `json:"name_2"`
	ArtistName string `json:"artist_name"`
}

// Search event name, venue name, or ANY performer name (entity or name-only).
func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, searchEvents, arg.Name, arg.Name_2, arg.ArtistName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.About,
			&i.StartDate,
			&i.EndDate,
			&i.HasTime,
			&i.VenueID,
			&i.Url,
			&i.ImageUrl,
			&i.TicketOptions,
			&i.ListingState,
			&i.Extra,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListingState = `-- name: SetListingState :exec
UPDATE events SET listing_state = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetListingStateParams struct {
	ListingState string `json:"listing_state"`
	ID           string `json:"id"`
}

func (q *Queries) SetListingState(ctx context.Context, arg SetListingStateParams) error {
	_, err := q.db.ExecContext(ctx, setListingState, arg.ListingState, arg.ID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    name = ?, kind = ?, description = ?, about = ?,
    start_date = ?, end_date = ?, has_time = ?, venue_id = ?, url = ?, image_url = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at
`

type UpdateEventParams struct {
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	Description sql.NullString `json:"description"`
	About       sql.NullString `json:"about"`
	StartDate   string         `json:"start_date"`
	EndDate     sql.NullString `json:"end_date"`
	HasTime     int64          `json:"has_time"`
	VenueID     sql.NullString `json:"venue_id"`
	Url         sql.NullString `json:"url"`
	ImageUrl    sql.NullString `json:"image_url"`
	ID          string         `json:"id"`
}

// Edits a (manual) event's mutable facts in place; identity + source unchanged.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.About,
		arg.StartDate,
		arg.EndDate,
		arg.HasTime,
		arg.VenueID,
		arg.Url,
		arg.ImageUrl,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.About,
		&i.StartDate,
		&i.EndDate,
		&i.HasTime,
		&i.VenueID,
		&i.Url,
		&i.ImageUrl,
		&i.TicketOptions,
		&i.ListingState,
		&i.Extra,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTmEvent = `-- name: UpsertTmEvent :one
INSERT INTO events (id, source, source_id, name, kind, description, about,
                    start_date, end_date, has_time, venue_id, url, image_url,
                    ticket_options, listing_state)
VALUES (?, 'ticketmaster', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'listed')
ON CONFLICT(source, source_id) WHERE source_id IS NOT NULL DO UPDATE SET
    name = excluded.name, kind = excluded.kind,
    description = excluded.description, about = excluded.about,
    start_date = excluded.start_date, end_date = excluded.end_date, has_time = excluded.has_time,
    venue_id = excluded.venue_id, url = excluded.url, image_url = excluded.image_url,
    ticket_options = excluded.ticket_options,
    listing_state = 'listed',                 -- TM has it => re-list it
    updated_at = CURRENT_TIMESTAMP
RETURNING id, source, source_id, name, kind, description, about, start_date, end_date, has_time, venue_id, url, image_url, ticket_options, listing_state, extra, discovered_at, created_at, updated_at
`

type UpsertTmEventParams struct {
	ID            string         `json:"id"`
	SourceID      sql.NullString `json:"source_id"`
	Name          string         `json:"name"`
	Kind          string         `json:"kind"`
	Description   sql.NullString `json:"description"`
	About         sql.NullString `json:"about"`
	StartDate     string         `json:"start_date"`
	EndDate       sql.NullString `json:"end_date"`
	HasTime       int64          `json:"has_time"`
	VenueID       sql.NullString `json:"venue_id"`
	Url           sql.NullString `json:"url"`
	ImageUrl      sql.NullString `json:"image_url"`
	TicketOptions string         `json:"ticket_options"`
}

// Upsert a TM event by its natural key. Conflict target matches the partial unique index.
func (q *Queries) UpsertTmEvent(ctx context.Context, arg UpsertTmEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, upsertTmEvent,
		arg.ID,
		arg.SourceID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.About,
		arg.StartDate,
		arg.EndDate,
		arg.HasTime,
		arg.VenueID,
		arg.Url,
		arg.ImageUrl,
		arg.TicketOptions,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.About,
		&i.StartDate,
		&i.EndDate,
		&i.HasTime,
		&i.VenueID,
		&i.Url,
		&i.ImageUrl,
		&i.TicketOptions,
		&i.ListingState,
		&i.Extra,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
