// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUserByStatus = `-- name: CountUserByStatus :one
SELECT COUNT(*) AS count FROM library_entries WHERE user_id = ? AND status = ?
`

type CountUserByStatusParams struct {
	UserID string `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) CountUserByStatus(ctx context.Context, arg CountUserByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLibraryEntry = `-- name: DeleteLibraryEntry :exec
DELETE FROM library_entries WHERE user_id = ? AND event_id = ?
`

type DeleteLibraryEntryParams struct {
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) DeleteLibraryEntry(ctx context.Context, arg DeleteLibraryEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteLibraryEntry, arg.UserID, arg.EventID)
	return err
}

const getLibraryEntry = `-- name: GetLibraryEntry :one
SELECT user_id, event_id, status, missed_reason, note, attended_date, created_at, updated_at FROM library_entries WHERE user_id = ? AND event_id = ?
`

type GetLibraryEntryParams struct {
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) GetLibraryEntry(ctx context.Context, arg GetLibraryEntryParams) (LibraryEntry, error) {
	row := q.db.QueryRowContext(ctx, getLibraryEntry, arg.UserID, arg.EventID)
	var i LibraryEntry
	err := row.Scan(
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.MissedReason,
		&i.Note,
		&i.AttendedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNeedsResolution = `-- name: ListNeedsResolution :many
SELECT le.user_id, le.event_id, le.status, le.missed_reason, le.note, le.attended_date, le.created_at, le.updated_at, e.name, e.start_date
FROM library_entries le JOIN events e ON e.id = le.event_id
WHERE le.user_id = ? AND le.status = 'going'
  AND date(e.start_date) < date('now')
ORDER BY e.start_date ASC
`

type ListNeedsResolutionRow struct {
	UserID       string         `json:"user_id"`
	EventID      string         `json:"event_id"`
	Status       string         `json:"status"`
	MissedReason sql.NullString `json:"missed_reason"`
	Note         sql.NullString `json:"note"`
	AttendedDate sql.NullString `json:"attended_date"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	Name         string         `json:"name"`
	StartDate    string         `json:"start_date"`
}

// "needs resolution": going + the date has passed (derived; for the attendance nudge).
func (q *Queries) ListNeedsResolution(ctx context.Context, userID string) ([]ListNeedsResolutionRow, error) {
	rows, err := q.db.QueryContext(ctx, listNeedsResolution, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNeedsResolutionRow{}
	for rows.Next() {
		var i ListNeedsResolutionRow
		if err := rows.Scan(
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.MissedReason,
			&i.Note,
			&i.AttendedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLibrary = `-- name: ListUserLibrary :many
SELECT user_id, event_id, status, missed_reason, note, attended_date, created_at, updated_at FROM library_entries WHERE user_id = ?
`

func (q *Queries) ListUserLibrary(ctx context.Context, userID string) ([]LibraryEntry, error) {
	rows, err := q.db.QueryContext(ctx, listUserLibrary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntry{}
	for rows.Next() {
		var i LibraryEntry
		if err := rows.Scan(
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.MissedReason,
			&i.Note,
			&i.AttendedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLibraryByStatus = `-- name: ListUserLibraryByStatus :many
SELECT le.user_id, le.event_id, le.status, le.missed_reason, le.note, le.attended_date, le.created_at, le.updated_at, e.start_date, e.name, e.listing_state
FROM library_entries le JOIN events e ON e.id = le.event_id
WHERE le.user_id = ? AND le.status = ?
ORDER BY e.start_date DESC
`

type ListUserLibraryByStatusParams struct {
	UserID string `json:"user_id"`
	Status string `json:"status"`
}

type ListUserLibraryByStatusRow struct {
	UserID       string         `json:"user_id"`
	EventID      string         `json:"event_id"`
	Status       string         `json:"status"`
	MissedReason sql.NullString `json:"missed_reason"`
	Note         sql.NullString `json:"note"`
	AttendedDate sql.NullString `json:"attended_date"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	StartDate    string         `json:"start_date"`
	Name         string         `json:"name"`
	ListingState string         `json:"listing_state"`
}

func (q *Queries) ListUserLibraryByStatus(ctx context.Context, arg ListUserLibraryByStatusParams) ([]ListUserLibraryByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserLibraryByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserLibraryByStatusRow{}
	for rows.Next() {
		var i ListUserLibraryByStatusRow
		if err := rows.Scan(
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.MissedReason,
			&i.Note,
			&i.AttendedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.Name,
			&i.ListingState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLibraryEntry = `-- name: UpsertLibraryEntry :one
INSERT INTO library_entries (user_id, event_id, status, missed_reason, note, attended_date)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, event_id) DO UPDATE SET
    status = excluded.status,
    missed_reason = excluded.missed_reason,
    note = excluded.note,
    attended_date = excluded.attended_date,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, event_id, status, missed_reason, note, attended_date, created_at, updated_at
`

type UpsertLibraryEntryParams struct {
	UserID       string         `json:"user_id"`
	EventID      string         `json:"event_id"`
	Status       string         `json:"status"`
	MissedReason sql.NullString `json:"missed_reason"`
	Note         sql.NullString `json:"note"`
	AttendedDate sql.NullString `json:"attended_date"`
}

func (q *Queries) UpsertLibraryEntry(ctx context.Context, arg UpsertLibraryEntryParams) (LibraryEntry, error) {
	row := q.db.QueryRowContext(ctx, upsertLibraryEntry,
		arg.UserID,
		arg.EventID,
		arg.Status,
		arg.MissedReason,
		arg.Note,
		arg.AttendedDate,
	)
	var i LibraryEntry
	err := row.Scan(
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.MissedReason,
		&i.Note,
		&i.AttendedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
