// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Artist struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	FetchMode string `json:"fetch_mode"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ArtistCategory struct {
	ArtistID   string `json:"artist_id"`
	CategoryID string `json:"category_id"`
	CreatedAt  string `json:"created_at"`
}

type Category struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	UserID    sql.NullString `json:"user_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Event struct {
	ID            string         `json:"id"`
	Source        string         `json:"source"`
	SourceID      sql.NullString `json:"source_id"`
	Name          string         `json:"name"`
	Kind          string         `json:"kind"`
	Description   sql.NullString `json:"description"`
	About         sql.NullString `json:"about"`
	StartDate     string         `json:"start_date"`
	EndDate       sql.NullString `json:"end_date"`
	HasTime       int64          `json:"has_time"`
	VenueID       sql.NullString `json:"venue_id"`
	Url           sql.NullString `json:"url"`
	ImageUrl      sql.NullString `json:"image_url"`
	TicketOptions string         `json:"ticket_options"`
	ListingState  string         `json:"listing_state"`
	Extra         string         `json:"extra"`
	DiscoveredAt  string         `json:"discovered_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type FetchLog struct {
	ID             string         `json:"id"`
	ArtistID       sql.NullString `json:"artist_id"`
	Source         string         `json:"source"`
	StartedAt      string         `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
	EventsFetched  sql.NullInt64  `json:"events_fetched"`
	EventsKept     sql.NullInt64  `json:"events_kept"`
	EventsInserted sql.NullInt64  `json:"events_inserted"`
	EventsUpdated  sql.NullInt64  `json:"events_updated"`
	EventsDeleted  sql.NullInt64  `json:"events_deleted"`
	EventsDelisted sql.NullInt64  `json:"events_delisted"`
}

type LibraryEntry struct {
	UserID       string         `json:"user_id"`
	EventID      string         `json:"event_id"`
	Status       string         `json:"status"`
	MissedReason sql.NullString `json:"missed_reason"`
	Note         sql.NullString `json:"note"`
	AttendedDate sql.NullString `json:"attended_date"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type Performance struct {
	ID          string         `json:"id"`
	EventID     string         `json:"event_id"`
	ArtistID    sql.NullString `json:"artist_id"`
	ArtistName  string         `json:"artist_name"`
	IsHeadliner int64          `json:"is_headliner"`
	Date        sql.NullString `json:"date"`
	VenueName   sql.NullString `json:"venue_name"`
	CreatedAt   string         `json:"created_at"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Role      string `json:"role"`
	Active    int64  `json:"active"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserSetting struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Venue struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	City        sql.NullString  `json:"city"`
	Country     sql.NullString  `json:"country"`
	CountryCode sql.NullString  `json:"country_code"`
	Latitude    sql.NullFloat64 `json:"latitude"`
	Longitude   sql.NullFloat64 `json:"longitude"`
	Timezone    sql.NullString  `json:"timezone"`
	Source      sql.NullString  `json:"source"`
	SourceID    sql.NullString  `json:"source_id"`
	CreatedAt   string          `json:"created_at"`
	UpdatedAt   string          `json:"updated_at"`
}
