// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const deleteUserSetting = `-- name: DeleteUserSetting :exec
DELETE FROM user_settings WHERE user_id = ? AND key = ?
`

type DeleteUserSettingParams struct {
	UserID string `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSetting, arg.UserID, arg.Key)
	return err
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT id, user_id, key, value, created_at, updated_at
FROM user_settings
WHERE user_id = ? AND key = ?
`

type GetUserSettingParams struct {
	UserID string `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSetting, arg.UserID, arg.Key)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :many
SELECT id, user_id, key, value, created_at, updated_at
FROM user_settings
WHERE user_id = ?
ORDER BY key
`

func (q *Queries) GetUserSettings(ctx context.Context, userID string) ([]UserSetting, error) {
	rows, err := q.db.QueryContext(ctx, getUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSetting{}
	for rows.Next() {
		var i UserSetting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserSetting = `-- name: UpsertUserSetting :one
INSERT INTO user_settings (id, user_id, key, value, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (user_id, key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, key, value, created_at, updated_at
`

type UpsertUserSettingParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertUserSetting,
		arg.ID,
		arg.UserID,
		arg.Key,
		arg.Value,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
