// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countVenueEvents = `-- name: CountVenueEvents :one
SELECT COUNT(*) AS count FROM events WHERE venue_id = ?
`

func (q *Queries) CountVenueEvents(ctx context.Context, venueID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVenueEvents, venueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = ?
`

func (q *Queries) DeleteVenue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVenue, id)
	return err
}

const getManualVenue = `-- name: GetManualVenue :one
SELECT id, name, city, country, country_code, latitude, longitude, timezone, source, source_id, created_at, updated_at FROM venues
WHERE source = 'manual'
  AND source_id IS NULL
  AND name = ?1 COLLATE NOCASE
  AND COALESCE(city, '') = ?2 COLLATE NOCASE
LIMIT 1
`

type GetManualVenueParams struct {
	Name string         `json:"name"`
	City sql.NullString `json:"city"`
}

// Manual venues carry no source_id, so venues_source_key cannot dedupe them; match on the
// fields the user actually typed. COLLATE NOCASE is ASCII-only - "Cafe" and "cafe" match,
// accented spellings do not.
func (q *Queries) GetManualVenue(ctx context.Context, arg GetManualVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getManualVenue, arg.Name, arg.City)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, city, country, country_code, latitude, longitude, timezone, source, source_id, created_at, updated_at FROM venues WHERE id = ?
`

func (q *Queries) GetVenue(ctx context.Context, id string) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueBySource = `-- name: GetVenueBySource :one
SELECT id, name, city, country, country_code, latitude, longitude, timezone, source, source_id, created_at, updated_at FROM venues WHERE source = ? AND source_id = ?
`

type GetVenueBySourceParams struct {
	Source   sql.NullString `json:"source"`
	SourceID sql.NullString `json:"source_id"`
}

func (q *Queries) GetVenueBySource(ctx context.Context, arg GetVenueBySourceParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueBySource, arg.Source, arg.SourceID)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, city, country, country_code, latitude, longitude, timezone, source, source_id, created_at, updated_at FROM venues ORDER BY name
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Country,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Source,
			&i.SourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesWithCounts = `-- name: ListVenuesWithCounts :many
SELECT v.id, v.name, v.city, v.country, v.country_code, v.latitude, v.longitude, v.timezone, v.source, v.source_id, v.created_at, v.updated_at, COUNT(e.id) AS event_count
FROM venues v
LEFT JOIN events e ON e.venue_id = v.id
GROUP BY v.id
ORDER BY v.name
`

type ListVenuesWithCountsRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	City        sql.NullString  `json:"city"`
	Country     sql.NullString  `json:"country"`
	CountryCode sql.NullString  `json:"country_code"`
	Latitude    sql.NullFloat64 `json:"latitude"`
	Longitude   sql.NullFloat64 `json:"longitude"`
	Timezone    sql.NullString  `json:"timezone"`
	Source      sql.NullString  `json:"source"`
	SourceID    sql.NullString  `json:"source_id"`
	CreatedAt   string          `json:"created_at"`
	UpdatedAt   string          `json:"updated_at"`
	EventCount  int64           `json:"event_count"`
}

func (q *Queries) ListVenuesWithCounts(ctx context.Context) ([]ListVenuesWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVenuesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVenuesWithCountsRow{}
	for rows.Next() {
		var i ListVenuesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Country,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Source,
			&i.SourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVenue = `-- name: UpsertVenue :one
INSERT INTO venues (id, name, city, country, country_code, latitude, longitude, timezone, source, source_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source, source_id) WHERE source_id IS NOT NULL DO UPDATE SET
    name = excluded.name, city = excluded.city, country = excluded.country,
    country_code = excluded.country_code, latitude = excluded.latitude,
    longitude = excluded.longitude, timezone = excluded.timezone, updated_at = CURRENT_TIMESTAMP
RETURNING id, name, city, country, country_code, latitude, longitude, timezone, source, source_id, created_at, updated_at
`

type UpsertVenueParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	City        sql.NullString  `json:"city"`
	Country     sql.NullString  `json:"country"`
	CountryCode sql.NullString  `json:"country_code"`
	Latitude    sql.NullFloat64 `json:"latitude"`
	Longitude   sql.NullFloat64 `json:"longitude"`
	Timezone    sql.NullString  `json:"timezone"`
	Source      sql.NullString  `json:"source"`
	SourceID    sql.NullString  `json:"source_id"`
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, upsertVenue,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Country,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.Timezone,
		arg.Source,
		arg.SourceID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
